# Generated by Django 4.2.3 on 2024-02-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_newsarticle"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="content",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="newsarticle",
            name="origin",
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="created",
            field=models.DateField(),
        ),
    ]
