# Generated by Django 4.2.3 on 2024-02-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_newsarticle_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="content",
            field=models.TextField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="created",
            field=models.DateField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="description",
            field=models.TextField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="origin",
            field=models.URLField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="newsarticle",
            name="title",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
