# Generated by Django 4.2.3 on 2024-02-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_alter_newsarticle_created_alter_newsarticle_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newsarticle",
            name="origin",
            field=models.URLField(null=True),
        ),
    ]
