# Generated by Django 4.2.3 on 2024-02-18 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_alter_newsarticle_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="dont_delete",
            field=models.BooleanField(default=False),
        ),
    ]
