# Generated by Django 4.2.3 on 2024-02-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_newsarticle_dont_delete"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsarticle",
            name="updated",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
