# Generated by Django 4.2.3 on 2024-02-18 12:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_newsarticle_updated"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="newsarticle",
            options={"ordering": ["-updated"]},
        ),
    ]
