# Generated by Django 4.2.4 on 2023-08-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='./images/profile_pics/default_pic.jpg', null=True, upload_to='./images/profile_pics'),
        ),
    ]
