# Generated by Django 4.2.1 on 2023-06-04 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='available_until',
            field=models.DateField(default=datetime.date(2023, 6, 11)),
        ),
    ]
