# Generated by Django 4.2.4 on 2023-08-24 11:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='available_until',
            field=models.DateField(default=datetime.date(2023, 8, 31)),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contact',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
