# Generated by Django 4.2.2 on 2023-06-08 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_file_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='available_until',
            field=models.DateField(default=datetime.date(2023, 6, 15)),
        ),
    ]
