# Generated by Django 4.2.4 on 2023-08-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_file_available_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='./static/images/profile_pics/default_pic.svg', null=True, upload_to='./static/images/profile_pics'),
        ),
    ]
