# Generated by Django 4.2.3 on 2023-07-27 11:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_file_available_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='available_until',
            field=models.DateField(default=datetime.date(2023, 8, 3)),
        ),
    ]
